/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Nominee =
	| {
        type: "world";
        /**
         * The name this world shows up as in user interfaces.
         */
        name: string;
        /**
         * The owner of this world.
         */
        owner: string;
        [k: string]: unknown;
	  }
	| {
        type: "player";
        /**
         * The name this player shows up as in user interfaces.
         */
        name: string;
        [k: string]: unknown;
	  }
	| {
        type: "team";
        /**
         * The name this team shows up as in user interfaces.
         */
        name: string;
        [k: string]: unknown;
	  };

/**
 * A schema for compiling the results of a Community LegitiAwards event.
 */
export interface CommunityLegitiAwardsResultsSchema {
	format_version: string;
	/**
	 * The name this result shows up as in user interfaces.
	 */
	display_name: string;
	/**
	 * ID of this result.
	 */
	id: string;
	/**
	 * When this event happened expressed as an ISO date-time string
	 */
	datetime: string;
	/**
	 * List of all nominees.
	 */
	nominees: {
		[k: string]: Nominee;
	};
	/**
	 * List of all winners.
	 */
	winners: Winner[];
	[k: string]: unknown;
}
export interface Winner {
	/**
	 * The name of the category.
	 */
	category_name: string;
	/**
	 * An identifier pointing to the winning nominee.
	 */
	winner: string;
	/**
	 * A list of identifiers pointing to nominees that didn't win.
	 */
	nominees: string[];
	[k: string]: unknown;
}
